print("hello world")
print("Jaana")
print("i missed you")
print("i can't lost you")
print("you're everything for me")
print("you're my sweetheart")
print("even thou you're my entire peaceful world")
print("we will always be togather no matter what")
print("And i know you'll never forget me")
